import Head from 'next/head'
import { useTezos } from '../hooks/useTezos'
import { CONTRACT_ADDRESS } from '../constants'

export default function Home() {
  const { connectWallet, disconnectWallet, Tezos, address } = useTezos()

  const enterRoom = async () => {
    const contract = await Tezos.wallet.at(CONTRACT_ADDRESS);
    await contract.methods.enterRoom(1, true).send({ amount: 1 })
  }

  const refund = async () => {
    const contract = await Tezos.wallet.at(CONTRACT_ADDRESS);
    await contract.methods.refund(address).send()
  }

  return (
    <div>
      <Head>
        <title>Orbi.tez</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className='container'>
        <h1>HOME</h1>
        <a onClick={() => connectWallet()} className='planet__btn btn btn--center'>CONNECT WALLET</a>
        <a onClick={() => disconnectWallet()} className='planet__btn btn btn--center'>DISCONNECT WALLET</a>
        <div>
          <a disabled={address == ''} className='planet__btn btn btn--center' onClick={() => enterRoom()}>Enter Room</a>
          <a disabled={address == ''} className='planet__btn btn btn--center' onClick={() => refund()}>Refund</a>
        </div>
        <a href='/dashboard' className='planet__btn btn btn--center'>DASHBOARD</a>
      </div>
    </div>
  )
}
